apiVersion: v1
name: kafka-chart
description: A Helm chart for the ACK service controller for  ()
version: v0.0.0-non-release-version
appVersion: v0.0.0-non-release-version
home: https://github.com/aws-controllers-k8s/kafka-controller
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
  - https://github.com/aws-controllers-k8s/kafka-controller
maintainers:
  - name: ACK Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/ack-admin
  - name:  Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/kafka-maintainer
keywords:
  - aws
  - kubernetes
  - kafka
